### ISSUE TITLE
Question: Why don`t we store pre-built image in registry like docker hub？

### ISSUE THREAD

**Issue by Xunzhuo** [proxy-wasm/proxy-wasm-cpp-sdk#101]
From what I have tried, the process of building docker image takes so long, and as other issues said, it`s possible to go wrong when building image. 

Is there any problem to push a pre-built image to docker hub to manage? If we want to use it to compile C++ to wasm, we can just pull directly from docker hub?

I just pushed to my hub, if i want to use it somewhere else,  I just run `docker pull bitliu/proxy-wasm-cpp-sdk:v2` to get this image to compile cpp to wasm.

**Comment by bianpengyuan** [comment]
For long term I think we only want to maintain bazel based build. https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/pull/71 is an attempt to achieve that, which has been pending for quite a while.

**Comment by Xunzhuo** [comment]
@bianpengyuan got it~Thanks~
