### ISSUE TITLE
Question: WasmRuntimeValues in Envoy

### ISSUE THREAD

**Issue by Xunzhuo** [proxy-wasm/proxy-wasm-cpp-sdk#105]
As envoy source code shows:
 
![image](https://user-images.githubusercontent.com/48784001/115530576-7b40ca00-a2c6-11eb-9767-e3d26c719162.png)

How can I run wasm in Wasmtime, Wavm.. instead of v8 engine in Envoy ?

I try to edit envoy config to change runtime field to wasmtime or wavm, but it seems not to work right.

Is it now Envoy just support v8 to run wasm or something else?

**Comment by PiotrSikora** [comment]
You need to compile Envoy with selected Wasm runtime (e.g. `bazel build --define wasm=wasmtime ...`).

But please keep issues in their respective repositories. This is Envoy question, not C++ SDK question.
