### ISSUE TITLE
Is there an http status code related API

### ISSUE THREAD

**Issue by CalbeeMing0530** [proxy-wasm/proxy-wasm-cpp-sdk#111]
How can I return an HttpResponse in my cpp project, for example, I can further set to return 200 or 403 http status code according to whether the field value contained in the request header matches certain rules, is there any such example? I don't see an API for returning the relevant http status code in the API documentation provided by github 

Is there an example of something like [envoy wasm rust](https://github.com/proxy-wasm/proxy-wasm-rust-sdk/blob/master/examples/http_auth_random.rs)?

**Comment by bianpengyuan** [comment]
You can find some example here: https://github.com/istio-ecosystem/wasm-extensions/blob/master/extensions/basic_auth/plugin.cc#L31

**Comment by CalbeeMing0530** [comment]
> You can find some example here: https://github.com/istio-ecosystem/wasm-extensions/blob/master/extensions/basic_auth/plugin.cc#L31

@bianpengyuan thans a lot, I will try it ,  hope to see more detailed API documentation in the future：-）
