### ISSUE TITLE
How to update content-length header after modifying response body via setBuffer(WasmBufferType::HttpResponseBody) ?

### ISSUE THREAD

**Issue by orangetangerine** [proxy-wasm/proxy-wasm-cpp-sdk#124]
Hi, I have a json response like `{"foo": "bar"}`. It's content-length is 14
I added a wasm to wrap the json response to sth like `{"code": 0, "err": "", data: {"foo": "bar"}}`. It's content-length is 44.
I tried calling `addResponseHeader("content-length", "44")` and `replaceResponseHeader("content-length", "44")` in `onResponseBody. Neither worked.
And curl complains: `curl: (18) transfer closed with 30 bytes remaining to read`.

How can I update content-length after response body is modified?
Thanks.

**Comment by PiotrSikora** [comment]
No, you cannot update headers after modifying resposne body, since headers are already sent to the client.

However, you don't really need the `Content-Length` header, and you can safely remove it before modifying the body.

**Comment by orangetangerine** [comment]
Thanks!
