### ISSUE TITLE
core occurs when No-Content is received after httpCall

### ISSUE THREAD

**Issue by dmsqls** [proxy-wasm/proxy-wasm-cpp-sdk#22]
hi. core occurs when 204 No-Content is received after httpCall.

For what reason? Please tell me the solution.

The core information is as follows

tanks.

[Envoy (Epoch 0)] [2020-05-22 01:54:01.119][32][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:83] Caught Segmentation fault, suspect faulting address 0x0
[Envoy (Epoch 0)] [2020-05-22 01:54:01.119][32][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:70] Backtrace (use tools/stack_decode.py to get line numbers):
[Envoy (Epoch 0)] [2020-05-22 01:54:01.119][32][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:71] Envoy version: 73f240a29bece92a8882a36893ccce07b4a54664/1.13.1-dev/Clean/RELEASE/BoringSSL
[Envoy (Epoch 0)] [2020-05-22 01:54:01.121][32][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #0: __restore_rt [0x7efdadd2c890]
[Envoy (Epoch 0)] [2020-05-22 01:54:01.156][32][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #1: Envoy::Http::AsyncRequestImpl::onComplete() [0x55b0d9a9cb6c]
[Envoy (Epoch 0)] [2020-05-22 01:54:01.181][32][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #2: Envoy::Http::AsyncStreamImpl::encodeHeaders() [0x55b0d9a9c375]
[Envoy (Epoch 0)] [2020-05-22 01:54:01.207][32][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #3: Envoy::Router::Filter::onUpstreamHeaders() [0x55b0d9aa8698]
[Envoy (Epoch 0)] [2020-05-22 01:54:01.233][32][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #4: Envoy::Router::Filter::UpstreamRequest::decodeHeaders() [0x55b0d9aaa7d6]
[Envoy (Epoch 0)] [2020-05-22 01:54:01.258][32][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #5: Envoy::Http::Http1::ConnPoolImpl::StreamWrapper::decodeHeaders() [0x55b0d9a25b8b]
[Envoy (Epoch 0)] [2020-05-22 01:54:01.283][32][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #6: Envoy::Http::StreamDecoderWrapper::decodeHeaders() [0x55b0d9a8c32c]
[Envoy (Epoch 0)] [2020-05-22 01:54:01.308][32][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #7: Envoy::Http::Http1::ClientConnectionImpl::onMessageComplete() [0x55b0d9b17016]
[Envoy (Epoch 0)] [2020-05-22 01:54:01.333][32][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #8: Envoy::Http::Http1::ConnectionImpl::onMessageCompleteBase() [0x55b0d9b1445e]
[Envoy (Epoch 0)] [2020-05-22 01:54:01.358][32][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #9: Envoy::Http::Http1::ConnectionImpl::$_8::__invoke() [0x55b0d9b184dd]
[Envoy (Epoch 0)] [2020-05-22 01:54:01.384][32][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #10: http_parser_execute [0x55b0d9beb052]
[Envoy (Epoch 0)] [2020-05-22 01:54:01.411][32][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #11: Envoy::Http::Http1::ConnectionImpl::dispatchSlice() [0x55b0d9b12f9a]
[Envoy (Epoch 0)] [2020-05-22 01:54:01.439][32][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #12: Envoy::Http::Http1::ConnectionImpl::dispatch() [0x55b0d9b12d7f]
[Envoy (Epoch 0)] [2020-05-22 01:54:01.464][32][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #13: Envoy::Http::CodecClient::onData() [0x55b0d9a8b4a8]
[Envoy (Epoch 0)] [2020-05-22 01:54:01.489][32][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #14: Envoy::Http::CodecClient::CodecReadFilter::onData() [0x55b0d9a8c1fd]
[Envoy (Epoch 0)] [2020-05-22 01:54:01.515][32][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #15: Envoy::Network::FilterManagerImpl::onContinueReading() [0x55b0d98bc5db]
[Envoy (Epoch 0)] [2020-05-22 01:54:01.542][32][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #16: Envoy::Network::ConnectionImpl::onReadReady() [0x55b0d98b904a]
[Envoy (Epoch 0)] [2020-05-22 01:54:01.569][32][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #17: Envoy::Network::ConnectionImpl::onFileEvent() [0x55b0d98b8b1d]
[Envoy (Epoch 0)] [2020-05-22 01:54:01.596][32][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #18: Envoy::Event::FileEventImpl::assignEvents()::$_0::__invoke() [0x55b0d98b35f0]
[Envoy (Epoch 0)] [2020-05-22 01:54:01.623][32][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #19: event_process_active_single_queue [0x55b0d9be49ab]
[Envoy (Epoch 0)] [2020-05-22 01:54:01.649][32][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #20: event_base_loop [0x55b0d9be323e]
[Envoy (Epoch 0)] [2020-05-22 01:54:01.675][32][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #21: Envoy::Server::WorkerImpl::threadRoutine() [0x55b0d98a9278]
[Envoy (Epoch 0)] [2020-05-22 01:54:01.700][32][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #22: Envoy::Thread::ThreadImplPosix::ThreadImplPosix()::$_0::__invoke() [0x55b0d9daf953]
[Envoy (Epoch 0)] [2020-05-22 01:54:01.700][32][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:75] #23: start_thread [0x7efdadd216db]
AsyncClient 0x55b0e04bb690, stream_id_: 12133954153073262449
&stream_info_: 
  StreamInfoImpl 0x55b0e04bb830, protocol_: 1, response_code_: 200, response_code_details_: via_upstream, health_check_request_: 0, route_name_: 
2020-05-22T01:54:02.415268Z	info	sds	node:router~192.168.135.53~istio-ingressgateway-5f884b4dbd-bf6q4.istio-system~istio-system.svc.cluster.local-2 resource:ROOTCA connection is terminated: rpc error: code = Canceled desc = context canceled
2020-05-22T01:54:02.415321Z	error	sds	Remote side closed connection
2020-05-22T01:54:02.415857Z	info	Envoy proxy is NOT ready: failed to get server info: Get http://127.0.0.1:15000/stats?usedonly&filter=server.state: dial tcp 127.0.0.1:15000: connect: connection refused
2020-05-22T01:54:02.415903Z	info	transport: loopyWriter.run returning. connection error: desc = "transport is closing"
2020-05-22T01:54:02.416120Z	info	sds	node:router~192.168.135.53~istio-ingressgateway-5f884b4dbd-bf6q4.istio-system~istio-system.svc.cluster.local-1 resource:default connection is terminated: rpc error: code = Canceled desc = context canceled
2020-05-22T01:54:02.416176Z	error	sds	Remote side closed connection
2020-05-22T01:54:02.418683Z	error	Epoch 0 exited with error: signal: segmentation fault (core dumped)
2020-05-22T01:54:02.418720Z	info	No more active epochs, terminating

**Comment by bianpengyuan** [comment]
Which build are you using to run the module? Seems like the same issue that is fixed by https://github.com/envoyproxy/envoy-wasm/pull/455

**Comment by dmsqls** [comment]
solved in istio version 1.6.1. Thank you.
