### ISSUE TITLE
How to set Environment variables for Envoy-Filter?

### ISSUE THREAD

**Issue by dmsqls** [proxy-wasm/proxy-wasm-cpp-sdk#32]
Hi. 

I want to use environment variables in EnvoyFilter, is there a way to set it?

I checked the environment variable with the code below but couldn't find anything.

****
extern char **environ;
bool testRootContext::onStart(size_t ul_config_size)
{
    for (int for_i = 0; environ[for_i] != NULL; for_i++) {
        LOG_ERROR(std::string("ENV==== "), std::string(environ[for_i]));
    }
    return true;
}
**** 

Let me know if there is a way to get the environment variable.

thanks.

**Comment by taegyunkim** [comment]
I don't know how to set environment variable, but you can define a configuration using protobuf. 

solo.io's WASME CLI supports it, so I guess there should be a way to do it using kubectl. 
https://docs.solo.io/web-assembly-hub/latest/tutorial_code/build_tutorials/building_cpp_filters/
https://github.com/solo-io/wasme/blob/master/example/cpp/filter.proto
