### ISSUE TITLE
how to  make http call in stream context

### ISSUE THREAD

**Issue by Masterlvng** [proxy-wasm/proxy-wasm-cpp-sdk#34]
Hi all,
I want to do some check operation by sending outgoing http request in onRequestHeaders, just like the mixer filter
However, Context dosen't have httpCall method currently, only RootContext have.
So how could I make it?

**Comment by taegyunkim** [comment]
https://github.com/envoyproxy/envoy-wasm/blob/140d4e539cf452278669c8cf06478fb08633956a/test/extensions/filters/http/wasm/test_data/async_call_cpp.cc#L31-L32

Get the root and call httpCall

**Comment by Masterlvng** [comment]
@taegyunkim thank you.
