### ISSUE TITLE
Wasm VM failed Wasm module is missing malloc function

### ISSUE THREAD

**Issue by AsynchronousResource** [proxy-wasm/proxy-wasm-cpp-sdk#57]
Does anyone know why something as simple as adding:
`std::random_device rd;`
to the onCreate() or anywhere else would cause this error?

**Comment by kyessenov** [comment]
It's probably because it is using a device /dev/urandom or something from
POSIX that's not available in Wasm.

**Comment by gbrail** [comment]
FWIW it seems like sometimes errors that cause the module to be unloadable,
like missing imports or exports, cause the "Wasm module is missing malloc
function" when the root cause is something else.

**Comment by AsynchronousResource** [comment]
Thanks @kyessenov that was the issue.

And yes @gbrail you are correct.. i've also noticed that without proper imports the wasm builds just fine it just fails to load!
