### ISSUE TITLE
Implementing network filter

### ISSUE THREAD

**Issue by alishir** [proxy-wasm/proxy-wasm-cpp-sdk#85]
Is it possible to use `proxy-wasm-cpp-sdk` for implementing L3 network filters?

**Comment by PiotrSikora** [comment]
There is support for L4 (TCP, no UDP yet), but it's unlikely there will ever be support for L3 (IP).

**Comment by alishir** [comment]
Thanks for your reply. Is there any example L4 filter using `proxy-wasm-cpp-sdk`? Unfortunately I could not figure out how I should implement the L4 filter using this SDK.

**Comment by PiotrSikora** [comment]
Not a production-ready example to follow, but hopefully enough to get you started:
https://github.com/envoyproxy/envoy/blob/d0f0ec28527c2be0fb2cb827ff6be8bf51c45f06/test/extensions/filters/network/wasm/test_data/test_cpp.cc

**Comment by alishir** [comment]
Thanks a lot.
