### ISSUE TITLE
Inconsistent number of HTTP request response callbacks

### ISSUE THREAD

**Issue by liuqi-sun** [proxy-wasm/proxy-wasm-cpp-sdk#97]
OnRequestHeaders and onResponseHeaders are called the same number of times when I test by "sudo curl http://10.73.87.60:8000/", but  OnRequestHeaders and onResponseHeaders are called differently when I perform stress testsby "./wrk -t4 -c400 -d1s --latency http://10.73.87.60:8000/", why?

**Comment by PiotrSikora** [comment]
As mentioned in https://github.com/envoyproxy/envoy/issues/15724, this is unrelated to Proxy-Wasm C++ SDK.
