### ISSUE TITLE
WASM SDK for istio 1.9 (Envoy v1.17.1)

### ISSUE THREAD

**Issue by stoader** [proxy-wasm/proxy-wasm-cpp-sdk#99]
Is there version of the SDK that is compatible with Istio 1.9 which is using Envoy v1.17.1 ?

If so can you point me to the right branch/tag/commit?

**Comment by PiotrSikora** [comment]
Do you have any issue using `master` branch?

**Comment by stoader** [comment]
@PiotrSikora is that stable for production use?
